osx_image: xcode61
language: objective-c
before_install: gem install cocoapods xcpretty obcd -N
cache: cocoapods
podfile: Example/Podfile
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail && xcodebuild -workspace Example/SSAccessibility.xcworkspace -scheme SSAccessibility -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" clean test | xcpretty -c
  - pod lib lint --quick
  - obcd --path SSAccessibility find HeaderStyle
